# Generated by Django 4.1.2 on 2022-10-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_attendance_attender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance", name="date", field=models.DateField(null=True),
        ),
    ]
