# Generated by Django 4.1.2 on 2022-10-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_attendance_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance", name="date", field=models.DateTimeField(null=True),
        ),
    ]
