# Generated by Django 4.1.2 on 2022-10-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_attendance_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance", name="date", field=models.DateField(null=True),
        ),
    ]
