# Generated by Django 4.1.2 on 2022-10-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_attend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="attender",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="attendance", name="date", field=models.DateField(null=True),
        ),
        migrations.DeleteModel(name="Attend",),
    ]
