# Generated by Django 4.1.2 on 2022-10-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_customer_email_alter_customer_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="is_present",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
